### PR TITLE
Many RNASeq pipline changes, (SUPPA, MISO, JunctionSeq)

### PR DESCRIPTION
**Pull request by alexpenson**

### CODE REVIEW

**Comment by lordzappo** [comment]
yeah, he's cool

**Review by lordzappo — COMMENTED** [review]
@alexpenson @md09 @kpjonsson  @CMBielski This change by alex says that all get basecounts will take less than an hour to run, so they can go in the short queue.  is that reasonable?

**Comment by kpjonsson** [comment]
I don't know the context of this but it'll obviously depend on the input MAF/VCF and the number of bams.

**Comment by lordzappo** [comment]
It's for all getbasecounts runs for every facets workflow using 0.3.6, so if it ever takes longer than 1hr, this breaks you.  does not affect 0.5.2+.

**Comment by kpjonsson** [comment]
Oh, that getbasecounts. Don't really know, likely true for all IMPACT samples, don't know about exomes and genomes.

**Comment by alexpenson** [comment]
It might break for WGS samples...
I thought it didn't kill the job until double the wait time though?

**Review by lordzappo — CHANGES_REQUESTED** [review]
I'm ready to approve this due to lack of response/lack of investment by stakeholders.   Can you push one more commit to this PR that puts your name and email in the command line help for the workflows you've created, and I will merge.

**Review by lordzappo — APPROVED** [review]

**Pull request merged**
